image: registry.gitlab.com/tumia/php/8.1-cli-dev

stages:
  - test

.php: &phpXX
  variables:
    COMPOSER_UPDATE_ARGUMENTS: " "
    PHP_VERSION: "8.1"
  image: registry.gitlab.com/tumia/php/${PHP_VERSION}-cli-dev
  stage: test
  script:
    - composer validate
    - composer update --no-interaction --optimize-autoloader --no-progress ${COMPOSER_UPDATE_ARGUMENTS}
    - XDEBUG_MODE=off phpcs --runtime-set testVersion ${PHP_VERSION}
    - XDEBUG_MODE=off psalm --php-version=${PHP_VERSION}
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --no-interaction --coverage-cobertura=phpunit.coverage.cobertura.xml
    - sed -i 's~ filename="~ filename="src/~' ./phpunit.coverage.cobertura.xml
    - XDEBUG_MODE=coverage infection --no-progress --no-interaction
  artifacts:
    reports:
      cobertura: phpunit.coverage.cobertura.xml

test_php74_lowest:
  <<: *phpXX
  variables:
    COMPOSER_UPDATE_ARGUMENTS: " --prefer-lowest "
    PHP_VERSION: "7.4"

test_php74:
  <<: *phpXX
  variables:
    COMPOSER_UPDATE_ARGUMENTS: ""
    PHP_VERSION: "7.4"

test_php80_lowest:
  <<: *phpXX
  variables:
    COMPOSER_UPDATE_ARGUMENTS: " --prefer-lowest "
    PHP_VERSION: "8.0"

test_php80:
  <<: *phpXX
  variables:
    COMPOSER_UPDATE_ARGUMENTS: ""
    PHP_VERSION: "8.0"

test_php81_lowest:
  <<: *phpXX
  variables:
    COMPOSER_UPDATE_ARGUMENTS: " --prefer-lowest "
    PHP_VERSION: "8.1"

test_php81:
  <<: *phpXX
  variables:
    COMPOSER_UPDATE_ARGUMENTS: ""
    PHP_VERSION: "8.1"
