image: registry.gitlab.com/tumia/php/8.1-cli-dev

stages:
  - test

test:
  image: registry.gitlab.com/tumia/php/${PHP_VERSION}-cli-dev
  parallel:
    matrix:
      - PHP_VERSION: ["7.4", "8.0", "8.1"]
        COMPOSER_UPDATE_ARGUMENTS: [ "", " --prefer-lowest "]
  stage: test
  script:
    - composer validate
    - composer update --no-interaction --optimize-autoloader --no-progress ${COMPOSER_UPDATE_ARGUMENTS}
    - XDEBUG_MODE=off phpcs --runtime-set testVersion ${PHP_VERSION}
    - XDEBUG_MODE=off psalm --php-version=${PHP_VERSION}
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --no-interaction --coverage-cobertura=phpunit.coverage.cobertura.xml
    - sed -i 's~ filename="~ filename="src/~' ./phpunit.coverage.cobertura.xml
    - XDEBUG_MODE=coverage infection --no-progress --no-interaction
  artifacts:
    reports:
      cobertura: phpunit.coverage.cobertura.xml
