version: "3"
services:
    cli74:
        image: registry.gitlab.com/tumia/php/7.4-cli-dev
        volumes:
            - .:/app

    cli81:
        image: registry.gitlab.com/tumia/php/8.1-cli-dev
        volumes:
            - .:/app
